### PR TITLE
deprecation refactor

### PR DESCRIPTION
**Pull request by drahnr**
this is huge refactor still ongoing but revamps oregano to 
- fit for the most parts with Gnome HIG (UI rework)
- fix warnings (including some potential marshal/closure bugs!)
- fix deprecations
  - remove stock icons entirely
  - get rid of inline UI definitions
  - ...
- ...

### CODE REVIEW

**Comment by drahnr** [comment]
Test signoff

**Comment by Michi1994** [comment]
Why are you doing so much without synchronizing "evolutionary"? This is somehow ballsy

**Comment by drahnr** [comment]
Because one thing caused another and that way you end up in an unfortunate situation. I got are based version ready just a few days ago.

**Comment by drahnr** [comment]
There is still some fallout besides the missing menubar which I am going to fix soon(TM)

**Pull request closed without merging**
