### PR TITLE
Several new features, bug fixes and code improvements

### PR DESCRIPTION
**Pull request by gtrentalancia**
Please merge, the latest commits in my repository include a couple of recent bug fixes and some code cleanup.

### CODE REVIEW

**Comment by gtrentalancia** [comment]
I don't know why, but it generated some merge conflicts. I have tried to resolve them and it appears now safe to merge.

If you can, please give it a quick test.

Thanks,

Guido

**Comment by gtrentalancia** [comment]
I have recently fixed other bugs, made more improvements and also added the Fourier analysis.

However, the concourse checks never complete for some strange reason...

**Comment by gtrentalancia** [comment]
They come at virtually no cost and keep the code backwards compatible. Gtk version 3.16 is a bit old, but for example, 3.22 is not old at all. Sometimes end users are not able to upgrade on their own because the system is administered by somebody else.

I suggest to keep the code backwards compatible, for example, until it is 10 releases old (so, drop the compatibility for 3.16 when 3.26 is out).

Are you ready to merge and create a proper new release ?

**Comment by drahnr** [comment]
This makes only sense until we can ship a flatpack version of oregano, but for the meantime, yes, this might make sense as long as it does not take over too much.

**Comment by drahnr** [comment]
You did a whole lot of work there, much appreciated! I will review in a week from now/ASAP.

**Comment by gtrentalancia** [comment]
The compiler warnings have also been greatly reduced !

We only need to tackle deprecated GtkAction, GtkUIManager and GtkStock/gtk_icon_factory (all very obsolete) and that is it to have 0 compiler warnings...

**Pull request merged**
